/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard/webhooks'
import { Route as DashboardWalletsRouteImport } from './routes/dashboard/wallets'
import { Route as DashboardWalletProvidersRouteImport } from './routes/dashboard/wallet-providers'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRoutingRouteImport } from './routes/dashboard/routing'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardApiLogsRouteImport } from './routes/dashboard/api-logs'
import { Route as DashboardApiKeyRouteImport } from './routes/dashboard/api-key'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/onboarding/workspace',
  path: '/onboarding/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/dashboard/webhooks',
  path: '/dashboard/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletsRoute = DashboardWalletsRouteImport.update({
  id: '/dashboard/wallets',
  path: '/dashboard/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletProvidersRoute =
  DashboardWalletProvidersRouteImport.update({
    id: '/dashboard/wallet-providers',
    path: '/dashboard/wallet-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/dashboard/transactions',
  path: '/dashboard/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoutingRoute = DashboardRoutingRouteImport.update({
  id: '/dashboard/routing',
  path: '/dashboard/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/dashboard/projects',
  path: '/dashboard/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApiLogsRoute = DashboardApiLogsRouteImport.update({
  id: '/dashboard/api-logs',
  path: '/dashboard/api-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApiKeyRoute = DashboardApiKeyRouteImport.update({
  id: '/dashboard/api-key',
  path: '/dashboard/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/api-logs': typeof DashboardApiLogsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/routing': typeof DashboardRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet-providers': typeof DashboardWalletProvidersRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/api-logs': typeof DashboardApiLogsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/routing': typeof DashboardRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet-providers': typeof DashboardWalletProvidersRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/api-logs': typeof DashboardApiLogsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/routing': typeof DashboardRoutingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet-providers': typeof DashboardWalletProvidersRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/api-key'
    | '/dashboard/api-logs'
    | '/dashboard/payments'
    | '/dashboard/projects'
    | '/dashboard/routing'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/wallet-providers'
    | '/dashboard/wallets'
    | '/dashboard/webhooks'
    | '/onboarding/welcome'
    | '/onboarding/workspace'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/api-key'
    | '/dashboard/api-logs'
    | '/dashboard/payments'
    | '/dashboard/projects'
    | '/dashboard/routing'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/wallet-providers'
    | '/dashboard/wallets'
    | '/dashboard/webhooks'
    | '/onboarding/welcome'
    | '/onboarding/workspace'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/api-key'
    | '/dashboard/api-logs'
    | '/dashboard/payments'
    | '/dashboard/projects'
    | '/dashboard/routing'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/wallet-providers'
    | '/dashboard/wallets'
    | '/dashboard/webhooks'
    | '/onboarding/welcome'
    | '/onboarding/workspace'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  DashboardApiKeyRoute: typeof DashboardApiKeyRoute
  DashboardApiLogsRoute: typeof DashboardApiLogsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRoutingRoute: typeof DashboardRoutingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWalletProvidersRoute: typeof DashboardWalletProvidersRoute
  DashboardWalletsRoute: typeof DashboardWalletsRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/onboarding/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/dashboard/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallets': {
      id: '/dashboard/wallets'
      path: '/dashboard/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof DashboardWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet-providers': {
      id: '/dashboard/wallet-providers'
      path: '/dashboard/wallet-providers'
      fullPath: '/dashboard/wallet-providers'
      preLoaderRoute: typeof DashboardWalletProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/routing': {
      id: '/dashboard/routing'
      path: '/dashboard/routing'
      fullPath: '/dashboard/routing'
      preLoaderRoute: typeof DashboardRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/api-logs': {
      id: '/dashboard/api-logs'
      path: '/dashboard/api-logs'
      fullPath: '/dashboard/api-logs'
      preLoaderRoute: typeof DashboardApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/api-key': {
      id: '/dashboard/api-key'
      path: '/dashboard/api-key'
      fullPath: '/dashboard/api-key'
      preLoaderRoute: typeof DashboardApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  DashboardApiKeyRoute: DashboardApiKeyRoute,
  DashboardApiLogsRoute: DashboardApiLogsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRoutingRoute: DashboardRoutingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWalletProvidersRoute: DashboardWalletProvidersRoute,
  DashboardWalletsRoute: DashboardWalletsRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
