/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard/webhooks'
import { Route as DashboardWalletProvidersRouteImport } from './routes/dashboard/wallet-providers'
import { Route as DashboardApiKeyRouteImport } from './routes/dashboard/api-key'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/dashboard/webhooks',
  path: '/dashboard/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletProvidersRoute =
  DashboardWalletProvidersRouteImport.update({
    id: '/dashboard/wallet-providers',
    path: '/dashboard/wallet-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardApiKeyRoute = DashboardApiKeyRouteImport.update({
  id: '/dashboard/api-key',
  path: '/dashboard/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/wallet-providers': typeof DashboardWalletProvidersRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/wallet-providers': typeof DashboardWalletProvidersRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/api-key': typeof DashboardApiKeyRoute
  '/dashboard/wallet-providers': typeof DashboardWalletProvidersRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-key'
    | '/dashboard/wallet-providers'
    | '/dashboard/webhooks'
    | '/onboarding/welcome'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-key'
    | '/dashboard/wallet-providers'
    | '/dashboard/webhooks'
    | '/onboarding/welcome'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/api-key'
    | '/dashboard/wallet-providers'
    | '/dashboard/webhooks'
    | '/onboarding/welcome'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardApiKeyRoute: typeof DashboardApiKeyRoute
  DashboardWalletProvidersRoute: typeof DashboardWalletProvidersRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/dashboard/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet-providers': {
      id: '/dashboard/wallet-providers'
      path: '/dashboard/wallet-providers'
      fullPath: '/dashboard/wallet-providers'
      preLoaderRoute: typeof DashboardWalletProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/api-key': {
      id: '/dashboard/api-key'
      path: '/dashboard/api-key'
      fullPath: '/dashboard/api-key'
      preLoaderRoute: typeof DashboardApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardApiKeyRoute: DashboardApiKeyRoute,
  DashboardWalletProvidersRoute: DashboardWalletProvidersRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
